import images from "./images";
const products = [
  {
    id: 1,
    name: "Short Skirt",
    price: 40,
    description: "Beautiful black skirt for beautiful ladies",
    image: images.clothes_4,
    quantity: 2,
  },
  {
    id: 2,
    name: "Leather Jacket",
    price: 60,
    description: "Brown Original leather jackets for guys",
    image: images.jacket_1,
    quantity: 5,
  },
  {
    id: 3,
    name: "Ear rings",
    price: 10,
    description: "Beautiful ear rings in all sizes for our beautiful ladies",
    image: images.jewellery_1,
    quantity: 10,
  },
  {
    id: 4,
    name: "High heel shoe",
    price: 30,
    description: "Brown high heel shoes for our ladies",
    image: images.party_wear_2,
    quantity: 4,
  },
  {
    id: 5,
    name: "Perfume",
    price: 27,
    description: "Scented perfumes for both gender",
    image: images.perfume,
    quantity: 8,
  },
  {
    id: 6,
    name: "Shampoo",
    price: 32,
    description: "Facial shampoo for our ladies",
    image: images.shampoo,
    quantity: 9,
  },
  {
    id: 7,
    name: "Long sleeve shirt",
    price: 43,
    description: "Violet long sleeve shirt for our guys in all sizes",
    image: images.shirt_1,
    quantity: 1,
  },
  {
    id: 8,
    name: "Black Shoe",
    price: 55,
    description: "Black polishable shoe for all occasions",
    image: images.shoe_3,
    quantity: 7,
  },
  {
    id: 9,
    name: "Jersey",
    price: 100,
    description: "All in sizes jersey top and down for ladies",
    image: images.shorts_1,
    quantity: 6,
  },
  {
    id: 10,
    name: "Sports Boot",
    price: 120,
    description: "Sport boots for both guys and ladies",
    image: images.sports_1,
    quantity: 5,
  },
  {
    id: 11,
    name: "Smart Watch",
    price: 150,
    description: "Smart watch that can be connected to your phone",
    image: images.watch_1,
    quantity: 4,
  },
  {
    id: 12,
    name: "Pocket Watch",
    price: 76,
    description: "Golden pocket watch",
    image: images.watch_4,
    quantity: 3,
  },
];
export default products;
